title: Windy Pardo
logo: /img/Fotografia Windy Pardo.jpg
description: >
  ğŸ“ BogotÃ¡, Colombia  
  ğŸ“§ vanepardo912@gmail.com  
  ğŸ”— [LinkedIn](https://linkedin.com/in/windy-vanesa-pardo) | 
  ğŸ”— [Portfolio](https://pardo0912.github.io/Portfolio/)
theme: jekyll-theme-minimal
