title: Windy Pardo
logo: /img/Fotografia Windy Pardo.jpg
description: >
  <p align="center">ğŸ“ BogotÃ¡, Colombia</p>
  <p align="center">ğŸ“§ <strong>vanepardo912@gmail.com</strong></p>
  <p align="center">ğŸ”— <a href="https://linkedin.com/in/windy-vanesa-pardo">LinkedIn</a> | <a href="https://pardo0912.github.io/Portfolio/">Portfolio</a></p>
theme: jekyll-theme-minimal-mistakes
