title: Windy Pardo
logo: /img/Fotografia Windy Pardo.jpg
description: >
  <p align="center">
    ğŸ“ BogotÃ¡, Colombia
  </p>
  <p align="center">
    ğŸ“§ <b>vanepardo912@gmail.com</b>
  </p>
  <p align="center">
    ğŸ”— <a href="https://linkedin.com/in/windy-vanesa-pardo" target="_blank">LinkedIn</a> |
    <a href="https://pardo0912.github.io/Portfolio/" target="_blank">Portfolio</a>
  </p>
theme: jekyll-theme-modernist
